services:
  refiner-message-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refiner-message-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
